logging:
  level:
    root: info
    com.example.video.dao: debug
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/c_video?serverTimezone=Asia/Shanghai&characterEncoding=UTF-8
    username: root
    password: 1234567
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 30000
  thymeleaf:
    cache: false